name: Publish to NPM
on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    env:
      AZURE_STORAGE_ENDPOINT: "http://localhost:10000/devstoreaccount1"
      AZURE_STORAGE_ACCOUNT_NAME: "devstoreaccount1"
      AZURE_STORAGE_ACCOUNT_KEY: "Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw=="
    services:
      storage:
        image: mcr.microsoft.com/azure-storage/azurite
        ports:
          - 10000:10000
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: 9.7.1

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml
          registry-url: https://registry.npmjs.org
          git-checks: false
          always-auth: true
          scope: "@yukonsky"

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Build & Test
        run: pnpm build && pnpm test

      - name: Publish
        run: pnpm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Get tag
        id: get-tag
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

      - name: Create release
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
        run: |
          echo "${{ github.sha }}" >> release-commit-hash
          gh release create "${{ steps.get-tag.outputs.tag }}" --generate-notes release-commit-hash
