name: Test
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/test.yml'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - 'src/**'
      - 'e2e/**'
  pull_request:
    paths:
      - '.github/workflows/test.yml'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - 'src/**'
      - 'e2e/**'

permissions:
  id-token: write
  contents: write
  actions: write
  checks: write
  pull-requests: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      AZURE_STORAGE_ENDPOINT: 'http://localhost:10000/devstoreaccount1'
      AZURE_STORAGE_ACCOUNT_NAME: 'devstoreaccount1'
      AZURE_STORAGE_ACCOUNT_KEY: 'Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw=='
    services:
      storage:
        image: mcr.microsoft.com/azure-storage/azurite
        ports:
          - 10000:10000
    timeout-minutes: 10
    steps:
      - name: Cancel previous workflow
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

      - shell: bash
        run: |
          if [ ${{ github.event_name }} == 'pull_request' ]; then
            echo "IS_PR=true" >> $GITHUB_ENV
          else
            echo "IS_PR=false" >> $GITHUB_ENV
          fi

      - name: Checkout
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 8.6.9

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: .node-version
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Run test
        run: pnpm test
